package com.leetcode.clone.Auth.dto;

public enum RegisterStatus {
    USER_CREATED,
    USER_ALREADY_EXISTS,
    REGISTRATION_FAILED,
    LOGIN_SUCCESSFULL,
    LOGIN_FAILED,
    USER_DOES_NOT_EXIST,
    REFRESH_TOKEN_SUCCESS,
    REFRESH_TOKEN_FAILED
}